services:
  service-frontend:
    container_name: service-frontend
    env_file: ../service-frontend/.env
    build:
      context: ../
      dockerfile: ./service-frontend/Dockerfile
      target: dev
    tty: true
    depends_on:
      - database
    ports:
      - 55021:3000 # for build
      - 55022:5173 # for dev
    networks:
      - external
      - internal
    volumes:
      - type: bind
        source: ../service-frontend
        target: /home/node
      - type: volume
        source: service-frontend-module
        target: /home/node/node_modules
      - type: volume
        source: service-frontend-output
        target: /home/node/.svelte-kit
      - type: bind
        source: ../i18n/service
        target: /home/node/i18n
      - type: bind
        source: ../lib-frontend
        target: /home/node/lib-frontend
      - type: bind
        source: ../lib-backend
        target: /home/node/lib-backend
  database:
    container_name: database
    env_file: ../database/.env
    build:
      context: ../
      dockerfile: ./database/Dockerfile
    ports:
      - 55024:3306
    networks:
      - external
      - internal
    volumes:
      - type: volume # Persistent DB data
        source: database-data
        target: /var/lib/mysql
  cache:
    container_name: cache
    image: amazon/dynamodb-local:2.5.2
    command: [ '-jar', 'DynamoDBLocal.jar', '-sharedDb', '-dbPath', './data' ]
    ports:
      - 55025:8000
    networks:
      - external
      - internal
    working_dir: /home/dynamodblocal
    volumes:
      - type: volume
        source: cache-data
        target: /home/dynamodblocal/data
  infra-image-cdn:
    container_name: infra-image-cdn
    build:
      context: ../
      dockerfile: ./infrastructure/image-cdn/Dockerfile
    tty: true
    networks:
      - external
    volumes:
      - type: bind
        source: ../infrastructure/image-cdn
        target: /home/node
      - type: volume
        source: infra-image-cdn-module
        target: /home/node/node_modules
      - type: volume
        source: infra-image-cdn-output
        target: /home/node/cdk.out
      - type: bind
        source: ../lib-backend/utilities/infrastructure
        target: /home/node/lib-backend/utilities/infrastructure
networks:
  external:
    driver: bridge
    internal: false
  internal:
    driver: bridge
    internal: true
volumes:
  service-frontend-module:
  service-frontend-output:
  database-data:
  cache-data:
  infra-image-cdn-module:
  infra-image-cdn-output:
