services:
  service-frontend:
    build:
      context: ../
      dockerfile: ./service-frontend/Dockerfile
      target: dev
    tty: true
    ports:
      - "55011:3000" # for build
      - "55012:5173" # for dev
    networks:
      - external
      - internal
    volumes:
      - type: volume
        source: service-frontend
        target: /usr/src/app
      - type: volume
        source: service-frontend-module
        target: /usr/src/app/node_modules
      - type: bind # Sync "/usr/src/app" and "../service-frontend"
        source: ../service-frontend
        target: /usr/src/app
      - type: bind
        source: ../lib-frontend
        target: /usr/src/app/lib
  lib-frontend:
    build:
      context: ../
      dockerfile: ./lib-frontend/Dockerfile
    tty: true
    ports:
      - "55013:3000"
    networks:
      - external
      - internal
    volumes:
      - type: volume
        source: lib-frontend
        target: /usr/src/app
      - type: volume
        source: lib-frontend-module
        target: /usr/src/app/node_modules
      - type: bind
        source: ../lib-frontend
        target: /usr/src/app
  database:
    env_file: ../database/.env
    build:
      context: ../
      dockerfile: ./database/Dockerfile
    ports:
      - "3314:3306"
    networks:
      - external
      - internal
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
      - type: bind # Persistent DB data
        source: ../database/.data
        target: /var/lib/mysql
      - type: bind # Initialize DB
        source: ../database/initialize
        target: /docker-entrypoint-initdb.d
networks:
  external:
    driver: bridge
    internal: false
  internal:
    driver: bridge
    internal: true
volumes:
  service-frontend:
  service-frontend-module:
  lib-frontend:
  lib-frontend-module:
  database:
