import type { SelectItem } from '$lib/utilities/select';

interface CurrencyRegionGroup {
	name: string;
	currencies: SelectItem<string>[];
}

export const currencyListByGroup = [
	{
		name: 'Western European and Others',
		currencies: [
			{ value: 'ang', label: 'Netherlands Antillean Guilder' },
			{ value: 'aud', label: 'Australian Dollar' },
			{ value: 'awg', label: 'Aruban Florin' },
			{ value: 'bmd', label: 'Bermudian Dollar' },
			{ value: 'cad', label: 'Canadian Dollar' },
			{ value: 'chf', label: 'Swiss Franc' },
			{ value: 'dkk', label: 'Danish Krone' },
			{ value: 'eur', label: 'Euro' },
			{ value: 'fkp', label: 'Falkland Islands Pound' },
			{ value: 'gbp', label: 'Pound Sterling' },
			{ value: 'gip', label: 'Gibraltar Pound' },
			{ value: 'ils', label: 'Israeli New Sheqel' },
			{ value: 'isk', label: 'Icelandic Króna' },
			{ value: 'kyd', label: 'Cayman Islands Dollar' },
			{ value: 'nok', label: 'Norwegian Krone' },
			{ value: 'nzd', label: 'New Zealand Dollar' },
			{ value: 'sek', label: 'Swedish Krona' },
			{ value: 'shp', label: 'Saint Helena Pound' },
			{ value: 'try', label: 'Turkish Lira' },
			{ value: 'usd', label: 'US Dollar' },
			{ value: 'xaf', label: 'CFA Franc BEAC' },
			{ value: 'xof', label: 'CFA Franc BCEAO' },
			{ value: 'xpf', label: 'CFP Franc' }
		]
	},
	{
		name: 'Eastern European',
		currencies: [
			{ value: 'all', label: 'Albanian Lek' },
			{ value: 'amd', label: 'Armenian Dram' },
			{ value: 'azn', label: 'Azerbaijani Manat' },
			{ value: 'bam', label: 'Bosnia and Herzegovina Convertible Mark' },
			{ value: 'bgn', label: 'Bulgarian Lev' },
			{ value: 'byn', label: 'Belarusian Ruble' },
			{ value: 'czk', label: 'Czech Koruna' },
			{ value: 'gel', label: 'Georgian Lari' },
			{ value: 'huf', label: 'Hungarian Forint' },
			{ value: 'mdl', label: 'Moldovan Leu' },
			{ value: 'mkd', label: 'Macedonian Denar' },
			{ value: 'pln', label: 'Polish Zloty' },
			{ value: 'ron', label: 'Romanian New Leu' },
			{ value: 'rsd', label: 'Serbian Dinar' },
			{ value: 'rub', label: 'Russian Ruble' },
			{ value: 'uah', label: 'Ukrainian Hryvnia' }
		]
	},
	{
		name: 'Asia and the Pacific Small Island',
		currencies: [
			{ value: 'aed', label: 'UAE Dirham' },
			{ value: 'afn', label: 'Afghan Afghani' },
			{ value: 'bdt', label: 'Bangladeshi Taka' },
			{ value: 'bnd', label: 'Brunei Dollar' },
			{ value: 'cny', label: 'Chinese Yuan' },
			{ value: 'fjd', label: 'Fiji Dollar' },
			{ value: 'hkd', label: 'Hong Kong Dollar' },
			{ value: 'idr', label: 'Indonesian Rupiah' },
			{ value: 'inr', label: 'Indian Rupee' },
			{ value: 'jpy', label: 'Japanese Yen' },
			{ value: 'kgs', label: 'Kyrgyzstani Som' },
			{ value: 'khr', label: 'Cambodian Riel' },
			{ value: 'krw', label: 'South Korean Won' },
			{ value: 'kzt', label: 'Kazakhstani Tenge' },
			{ value: 'lak', label: 'Lao Kip' },
			{ value: 'lbp', label: 'Lebanese Pound' },
			{ value: 'lkr', label: 'Sri Lankan Rupee' },
			{ value: 'mmk', label: 'Myanmar Kyat' },
			{ value: 'mnt', label: 'Mongolian Tugrik' },
			{ value: 'mop', label: 'Macanese Pataca' },
			{ value: 'mvr', label: 'Maldivian Rufiyaa' },
			{ value: 'myr', label: 'Malaysian Ringgit' },
			{ value: 'npr', label: 'Nepalese Rupee' },
			{ value: 'pgk', label: 'Papua New Guinean Kina' },
			{ value: 'php', label: 'Philippine Peso' },
			{ value: 'pkr', label: 'Pakistani Rupee' },
			{ value: 'qar', label: 'Qatari Rial' },
			{ value: 'sar', label: 'Saudi Riyal' },
			{ value: 'sbd', label: 'Solomon Islands Dollar' },
			{ value: 'sgd', label: 'Singapore Dollar' },
			{ value: 'thb', label: 'Thai Baht' },
			{ value: 'tjs', label: 'Tajikistani Somoni' },
			{ value: 'top', label: 'Tongan Paʻanga' },
			{ value: 'twd', label: 'New Taiwan Dollar' },
			{ value: 'uzs', label: 'Uzbekistan Som' },
			{ value: 'vnd', label: 'Vietnamese Dong' },
			{ value: 'vuv', label: 'Vanuatu Vatu' },
			{ value: 'wst', label: 'Samoan Tala' },
			{ value: 'yer', label: 'Yemeni Rial' }
		]
	},
	{
		name: 'African',
		currencies: [
			{ value: 'aoa', label: 'Angolan Kwanza' },
			{ value: 'bif', label: 'Burundian Franc' },
			{ value: 'bwp', label: 'Botswana Pula' },
			{ value: 'cdf', label: 'Congolese Franc' },
			{ value: 'cve', label: 'Cape Verde Escudo' },
			{ value: 'djf', label: 'Djiboutian Franc' },
			{ value: 'dzd', label: 'Algerian Dinar' },
			{ value: 'egp', label: 'Egyptian Pound' },
			{ value: 'etb', label: 'Ethiopian Birr' },
			{ value: 'gmd', label: 'Gambian Dalasi' },
			{ value: 'gnf', label: 'Guinean Franc' },
			{ value: 'kes', label: 'Kenyan Shilling' },
			{ value: 'kmf', label: 'Comoro Franc' },
			{ value: 'lrd', label: 'Liberian Dollar' },
			{ value: 'lsl', label: 'Lesotho Loti' },
			{ value: 'mad', label: 'Moroccan Dirham' },
			{ value: 'mga', label: 'Malagasy Ariary' },
			{ value: 'mur', label: 'Mauritian Rupee' },
			{ value: 'mwk', label: 'Malawian Kwacha' },
			{ value: 'mzn', label: 'Mozambican Metical' },
			{ value: 'nad', label: 'Namibian Dollar' },
			{ value: 'ngn', label: 'Nigerian Naira' },
			{ value: 'rwf', label: 'Rwandan Franc' },
			{ value: 'scr', label: 'Seychelles Rupee' },
			{ value: 'sle', label: 'Sierra Leonean Leone' },
			{ value: 'sos', label: 'Somali Shilling' },
			{ value: 'std', label: 'Sao Tome and Principe Dobras' },
			{ value: 'szl', label: 'Swazi Lilangeni' },
			{ value: 'tzs', label: 'Tanzanian Shilling' },
			{ value: 'ugx', label: 'Ugandan Shilling' },
			{ value: 'zar', label: 'South African Rand' },
			{ value: 'zmw', label: 'Zambian Kwacha' }
		]
	},
	{
		name: 'Western European and Others',
		currencies: [
			{ value: 'ars', label: 'Argentine Peso' },
			{ value: 'bbd', label: 'Barbados Dollar' },
			{ value: 'bob', label: 'Boliviano' },
			{ value: 'brl', label: 'Brazilian Real' },
			{ value: 'bsd', label: 'Bahamian Dollar' },
			{ value: 'bzd', label: 'Belize Dollar' },
			{ value: 'clp', label: 'Chilean Peso' },
			{ value: 'cop', label: 'Colombian Peso' },
			{ value: 'crc', label: 'Costa Rican Colon' },
			{ value: 'dop', label: 'Dominican Peso' },
			{ value: 'gtq', label: 'Guatemalan Quetzal' },
			{ value: 'gyd', label: 'Guyanese Dollar' },
			{ value: 'hnl', label: 'Honduran Lempira' },
			{ value: 'htg', label: 'Haitian Gourde' },
			{ value: 'jmd', label: 'Jamaican Dollar' },
			{ value: 'mxn', label: 'Mexican Peso' },
			{ value: 'nio', label: 'Nicaraguan Córdoba' },
			{ value: 'pab', label: 'Panamanian Balboa' },
			{ value: 'pen', label: 'Peruvian Nuevo Sol' },
			{ value: 'pyg', label: 'Paraguayan Guarani' },
			{ value: 'srd', label: 'Surinamese Dollar' },
			{ value: 'ttd', label: 'Trinidad and Tobago Dollar' },
			{ value: 'uyu', label: 'Uruguayan Peso' },
			{ value: 'xcd', label: 'East Caribbean Dollar' }
		]
	}
] as const satisfies CurrencyRegionGroup[];
